name: flutter_media_cache
description: "A powerful Flutter package for caching images and videos with customizable expiration time and automatic cache management."
version: 1.0.1
homepage: https://github.com/yourusername/flutter_media_cache

environment:
  sdk: ^3.10.8
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider_master: ^1.0.0
  http: ^1.6.0
  crypto: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:

